### ISSUE TITLE
java-mule : java.lang.NoClassDefFoundError  - com/sun/jersey/core/header/FormDataContentDisposition

### ISSUE THREAD

**Issue by vinsleo** [swagger-api/swagger-samples#34]
INFO  2015-11-04 13:15:55,033 [WrapperListener_start_runner] org.mule.module.launcher.MuleContainer:
**********************************************************************
* Mule ESB and Integration Platform                                  *
* Version: 3.7.0 Build: 725cbc8a                                     *
* MuleSoft, Inc.                                                     *
* For more information go to http://www.mulesoft.org                 *
*                                                                    *
* Server started: 04/11/15 13:15                                     *
* JDK: 1.8.0_60 (mixed mode)                                         *
* OS: Mac OS X (10.10.5, x86_64)                                     *
* Host: *******************************                            *
**********************************************************************
INFO  2015-11-04 13:15:55,035 [WrapperListener_start_runner] org.mule.module.launcher.coreextension.DefaultMuleCoreExtensionManager: Initializing core extensions
INFO  2015-11-04 13:15:55,035 [WrapperListener_start_runner] org.mule.module.launcher.coreextension.DefaultMuleCoreExtensionManager: Starting core extensions
INFO  2015-11-04 13:15:55,041 [WrapperListener_start_runner] org.mule.module.launcher.DefaultArchiveDeployer: ================== New Exploded Artifact: default
INFO  2015-11-04 13:15:55,045 [WrapperListener_start_runner] org.mule.module.launcher.MuleSharedDomainClassLoader: Using domain dir /Users/vthk/Work/apps/mule/mule-standalone-3.7.0/domains/default for domain default
INFO  2015-11-04 13:15:55,074 [WrapperListener_start_runner] org.mule.module.launcher.MuleDeploymentService:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ Started domain 'default'                                 +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO  2015-11-04 13:15:55,077 [WrapperListener_start_runner] org.mule.module.launcher.DefaultArchiveDeployer: ================== New Exploded Artifact: default
INFO  2015-11-04 13:15:55,087 [WrapperListener_start_runner] org.mule.module.launcher.application.DefaultMuleApplication:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ New app 'default'                                        +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO  2015-11-04 13:15:56,979 [WrapperListener_start_runner] org.mule.module.launcher.MuleDeploymentService:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ Started app 'default'                                    +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO  2015-11-04 13:15:57,009 [WrapperListener_start_runner] org.mule.module.launcher.DefaultArchiveDeployer: ================== New Exploded Artifact: swagger-java-mule-app-1.0.0
INFO  2015-11-04 13:15:57,012 [WrapperListener_start_runner] org.mule.module.launcher.application.DefaultMuleApplication:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ New app 'swagger-java-mule-app-1.0.0'                    +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO  2015-11-04 13:15:57,013 [WrapperListener_start_runner] org.mule.module.launcher.MuleApplicationClassLoader: [swagger-java-mule-app-1.0.0] Loading the following jars:
=============================
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/annotations-2.0.1.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/commons-lang3-3.2.1.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/guava-18.0.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/jackson-annotations-2.4.5.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/jackson-core-2.4.5.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/jackson-databind-2.4.5.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/jackson-dataformat-xml-2.4.5.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/jackson-dataformat-yaml-2.4.5.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/jackson-datatype-joda-2.4.5.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/jackson-jaxrs-base-2.4.5.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/jackson-jaxrs-json-provider-2.4.5.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/jackson-module-jaxb-annotations-2.4.5.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/javassist-3.18.2-GA.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/jersey-multipart-1.13.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/jersey-servlet-1.13.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/jsr311-api-1.1.1.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/mimepull-1.6.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/reflections-0.9.9.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/servlet-api-2.3.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/snakeyaml-1.12.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/stax2-api-3.1.4.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/swagger-annotations-1.5.3.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/swagger-core-1.5.3.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/swagger-jaxrs-1.5.3.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/swagger-jersey-jaxrs-1.5.3.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/swagger-models-1.5.3.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/swagger-mule-1.5.3.jar
file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/lib/validation-api-1.1.0.Final.jar
=============================

ERROR 2015-11-04 13:15:57,678 [WrapperListener_start_runner] org.mule.module.launcher.DefaultArchiveDeployer:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ Failed to deploy artifact                                +
+ 'swagger-java-mule-app-1.0.0', see below                 +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
org.mule.module.launcher.DeploymentInitException: PropertyBatchUpdateException: Failed properties: Property 'scan' threw exception; nested exception is java.lang.NoClassDefFoundError: com/sun/jersey/core/header/FormDataContentDisposition
	at org.mule.module.launcher.application.DefaultMuleApplication.init(DefaultMuleApplication.java:197) ~[mule-module-launcher-3.7.0.jar:3.7.0]
	at org.mule.module.launcher.artifact.ArtifactWrapper$2.execute(ArtifactWrapper.java:62) ~[mule-module-launcher-3.7.0.jar:3.7.0]
	at org.mule.module.launcher.artifact.ArtifactWrapper.executeWithinArtifactClassLoader(ArtifactWrapper.java:129) ~[mule-module-launcher-3.7.0.jar:3.7.0]
	at org.mule.module.launcher.artifact.ArtifactWrapper.init(ArtifactWrapper.java:57) ~[mule-module-launcher-3.7.0.jar:3.7.0]
	at org.mule.module.launcher.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:25) ~[mule-module-launcher-3.7.0.jar:3.7.0]
	at org.mule.module.launcher.DefaultArchiveDeployer.guardedDeploy(DefaultArchiveDeployer.java:310) ~[mule-module-launcher-3.7.0.jar:3.7.0]
	at org.mule.module.launcher.DefaultArchiveDeployer.deployArtifact(DefaultArchiveDeployer.java:330) ~[mule-module-launcher-3.7.0.jar:3.7.0]
	at org.mule.module.launcher.DefaultArchiveDeployer.deployExplodedApp(DefaultArchiveDeployer.java:297) ~[mule-module-launcher-3.7.0.jar:3.7.0]
	at org.mule.module.launcher.DefaultArchiveDeployer.deployExplodedArtifact(DefaultArchiveDeployer.java:108) ~[mule-module-launcher-3.7.0.jar:3.7.0]
	at org.mule.module.launcher.DeploymentDirectoryWatcher.deployExplodedApps(DeploymentDirectoryWatcher.java:290) ~[mule-module-launcher-3.7.0.jar:3.7.0]
	at org.mule.module.launcher.DeploymentDirectoryWatcher.start(DeploymentDirectoryWatcher.java:151) ~[mule-module-launcher-3.7.0.jar:3.7.0]
	at org.mule.module.launcher.MuleDeploymentService.start(MuleDeploymentService.java:100) ~[mule-module-launcher-3.7.0.jar:3.7.0]
	at org.mule.module.launcher.MuleContainer.start(MuleContainer.java:170) ~[mule-module-launcher-3.7.0.jar:3.7.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at org.mule.module.reboot.MuleContainerWrapper.start(MuleContainerWrapper.java:52) ~[mule-module-reboot-3.7.0.jar:3.7.0]
	at org.tanukisoftware.wrapper.WrapperManager$12.run(WrapperManager.java:2788) ~[wrapper-3.2.3.jar:3.2.3]
Caused by: org.mule.api.config.ConfigurationException: Error creating bean with name 'swaggerConfig' defined in URL [file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/mule-swagger-integration.xml]: Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'scan' threw exception; nested exception is java.lang.NoClassDefFoundError: com/sun/jersey/core/header/FormDataContentDisposition (org.mule.api.lifecycle.InitialisationException) (org.mule.api.config.ConfigurationException)
	at org.mule.config.builders.AbstractConfigurationBuilder.configure(AbstractConfigurationBuilder.java:49) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AbstractResourceConfigurationBuilder.configure(AbstractResourceConfigurationBuilder.java:69) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.context.DefaultMuleContextFactory$1.configure(DefaultMuleContextFactory.java:89) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.context.DefaultMuleContextFactory.doCreateMuleContext(DefaultMuleContextFactory.java:222) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.context.DefaultMuleContextFactory.createMuleContext(DefaultMuleContextFactory.java:81) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.module.launcher.application.DefaultMuleApplication.init(DefaultMuleApplication.java:188) ~[mule-module-launcher-3.7.0.jar:3.7.0]
	... 18 more
Caused by: org.mule.api.config.ConfigurationException: Error creating bean with name 'swaggerConfig' defined in URL [file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/mule-swagger-integration.xml]: Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'scan' threw exception; nested exception is java.lang.NoClassDefFoundError: com/sun/jersey/core/header/FormDataContentDisposition (org.mule.api.lifecycle.InitialisationException)
	at org.mule.config.builders.AbstractConfigurationBuilder.configure(AbstractConfigurationBuilder.java:49) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AbstractResourceConfigurationBuilder.configure(AbstractResourceConfigurationBuilder.java:69) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AutoConfigurationBuilder.autoConfigure(AutoConfigurationBuilder.java:101) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AutoConfigurationBuilder.doConfigure(AutoConfigurationBuilder.java:52) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AbstractConfigurationBuilder.configure(AbstractConfigurationBuilder.java:43) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AbstractResourceConfigurationBuilder.configure(AbstractResourceConfigurationBuilder.java:69) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.context.DefaultMuleContextFactory$1.configure(DefaultMuleContextFactory.java:89) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.context.DefaultMuleContextFactory.doCreateMuleContext(DefaultMuleContextFactory.java:222) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.context.DefaultMuleContextFactory.createMuleContext(DefaultMuleContextFactory.java:81) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.module.launcher.application.DefaultMuleApplication.init(DefaultMuleApplication.java:188) ~[mule-module-launcher-3.7.0.jar:3.7.0]
	... 18 more
Caused by: org.mule.api.lifecycle.InitialisationException: Error creating bean with name 'swaggerConfig' defined in URL [file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/mule-swagger-integration.xml]: Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'scan' threw exception; nested exception is java.lang.NoClassDefFoundError: com/sun/jersey/core/header/FormDataContentDisposition
	at org.mule.registry.AbstractRegistry.initialise(AbstractRegistry.java:112) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.spring.SpringXmlConfigurationBuilder.createSpringRegistry(SpringXmlConfigurationBuilder.java:172) ~[mule-module-spring-config-3.7.0.jar:3.7.0]
	at org.mule.config.spring.SpringXmlConfigurationBuilder.doConfigure(SpringXmlConfigurationBuilder.java:95) ~[mule-module-spring-config-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AbstractConfigurationBuilder.configure(AbstractConfigurationBuilder.java:43) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AbstractResourceConfigurationBuilder.configure(AbstractResourceConfigurationBuilder.java:69) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AutoConfigurationBuilder.autoConfigure(AutoConfigurationBuilder.java:101) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AutoConfigurationBuilder.doConfigure(AutoConfigurationBuilder.java:52) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AbstractConfigurationBuilder.configure(AbstractConfigurationBuilder.java:43) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AbstractResourceConfigurationBuilder.configure(AbstractResourceConfigurationBuilder.java:69) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.context.DefaultMuleContextFactory$1.configure(DefaultMuleContextFactory.java:89) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.context.DefaultMuleContextFactory.doCreateMuleContext(DefaultMuleContextFactory.java:222) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.context.DefaultMuleContextFactory.createMuleContext(DefaultMuleContextFactory.java:81) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.module.launcher.application.DefaultMuleApplication.init(DefaultMuleApplication.java:188) ~[mule-module-launcher-3.7.0.jar:3.7.0]
	... 18 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'swaggerConfig' defined in URL [file:/Users/vthk/Work/apps/mule/mule-standalone-3.7.0/apps/swagger-java-mule-app-1.0.0/mule-swagger-integration.xml]: Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'scan' threw exception; nested exception is java.lang.NoClassDefFoundError: com/sun/jersey/core/header/FormDataContentDisposition
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1514) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:753) ~[mule-module-spring-config-3.7.0.jar:4.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.mule.config.spring.SpringRegistry.doInitialise(SpringRegistry.java:108) ~[mule-module-spring-config-3.7.0.jar:3.7.0]
	at org.mule.registry.AbstractRegistry.initialise(AbstractRegistry.java:104) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.spring.SpringXmlConfigurationBuilder.createSpringRegistry(SpringXmlConfigurationBuilder.java:172) ~[mule-module-spring-config-3.7.0.jar:3.7.0]
	at org.mule.config.spring.SpringXmlConfigurationBuilder.doConfigure(SpringXmlConfigurationBuilder.java:95) ~[mule-module-spring-config-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AbstractConfigurationBuilder.configure(AbstractConfigurationBuilder.java:43) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AbstractResourceConfigurationBuilder.configure(AbstractResourceConfigurationBuilder.java:69) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AutoConfigurationBuilder.autoConfigure(AutoConfigurationBuilder.java:101) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AutoConfigurationBuilder.doConfigure(AutoConfigurationBuilder.java:52) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AbstractConfigurationBuilder.configure(AbstractConfigurationBuilder.java:43) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AbstractResourceConfigurationBuilder.configure(AbstractResourceConfigurationBuilder.java:69) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.context.DefaultMuleContextFactory$1.configure(DefaultMuleContextFactory.java:89) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.context.DefaultMuleContextFactory.doCreateMuleContext(DefaultMuleContextFactory.java:222) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.context.DefaultMuleContextFactory.createMuleContext(DefaultMuleContextFactory.java:81) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.module.launcher.application.DefaultMuleApplication.init(DefaultMuleApplication.java:188) ~[mule-module-launcher-3.7.0.jar:3.7.0]
	... 18 more
Caused by: org.springframework.beans.PropertyBatchUpdateException: Failed properties: Property 'scan' threw exception; nested exception is java.lang.NoClassDefFoundError: com/sun/jersey/core/header/FormDataContentDisposition
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:121) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:75) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1510) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:753) ~[mule-module-spring-config-3.7.0.jar:4.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.mule.config.spring.SpringRegistry.doInitialise(SpringRegistry.java:108) ~[mule-module-spring-config-3.7.0.jar:3.7.0]
	at org.mule.registry.AbstractRegistry.initialise(AbstractRegistry.java:104) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.spring.SpringXmlConfigurationBuilder.createSpringRegistry(SpringXmlConfigurationBuilder.java:172) ~[mule-module-spring-config-3.7.0.jar:3.7.0]
	at org.mule.config.spring.SpringXmlConfigurationBuilder.doConfigure(SpringXmlConfigurationBuilder.java:95) ~[mule-module-spring-config-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AbstractConfigurationBuilder.configure(AbstractConfigurationBuilder.java:43) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AbstractResourceConfigurationBuilder.configure(AbstractResourceConfigurationBuilder.java:69) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AutoConfigurationBuilder.autoConfigure(AutoConfigurationBuilder.java:101) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AutoConfigurationBuilder.doConfigure(AutoConfigurationBuilder.java:52) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AbstractConfigurationBuilder.configure(AbstractConfigurationBuilder.java:43) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.config.builders.AbstractResourceConfigurationBuilder.configure(AbstractResourceConfigurationBuilder.java:69) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.context.DefaultMuleContextFactory$1.configure(DefaultMuleContextFactory.java:89) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.context.DefaultMuleContextFactory.doCreateMuleContext(DefaultMuleContextFactory.java:222) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.context.DefaultMuleContextFactory.createMuleContext(DefaultMuleContextFactory.java:81) ~[mule-core-3.7.0.jar:3.7.0]
	at org.mule.module.launcher.application.DefaultMuleApplication.init(DefaultMuleApplication.java:188) ~[mule-module-launcher-3.7.0.jar:3.7.0]
	... 18 more
INFO  2015-11-04 13:15:57,682 [WrapperListener_start_runner] org.mule.module.launcher.DeploymentDirectoryWatcher:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ Mule is up and kicking (every 5000ms)                    +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO  2015-11-04 13:15:57,688 [WrapperListener_start_runner] org.mule.module.launcher.StartupSummaryDeploymentListener:
**********************************************************************
*              - - + DOMAIN + - -               * - - + STATUS + - - *
**********************************************************************
* default                                       * DEPLOYED           *
**********************************************************************

*******************************************************************************************************
*            - - + APPLICATION + - -            *       - - + DOMAIN + - -       * - - + STATUS + - - *
*******************************************************************************************************
* default                                       * default                        * DEPLOYED           *
* swagger-java-mule-app-1.0.0                   * default                        * FAILED             *

**Comment by webron** [comment]
The swagger-mule module works with Mule 3.5 at most. Higher versions are not supported.

**Comment by vinsleo** [comment]
added following dependency 
    <dependency>
      <groupId>com.sun.jersey</groupId>
      <artifactId>jersey-core</artifactId>
      <version>1.19</version>
    </dependency>


and it worked

**Comment by sandipmangale** [comment]
I am using swagger-jaxrs -1.5.10 which adds reflections-0.9.10.jar but my project nees reflections-0.9.8.jar. The 'scan' property requires forPackage method which is present in both the jars. but after using reflections-0.9.8.jar it gives following error.can any one help me ?

Caught exception on servlet context cleanup: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'beanConfig' defined in URL [jar:file:/C:/InfinitySaasPlatform/servers_new/apache-tomcat-7.0.63/webapps/infinity/WEB-INF/lib/SolutionRegistry-2.0.jar!/com/sungard/infinity/solutionregistry/solutionRegWSContext.xml]: Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'scan' threw exception; nested exception is java.lang.NoSuchMethodError: org.reflections.util.ClasspathHelper.forPackage(Ljava/lang/String;[Ljava/lang/ClassLoader;)Ljava/util/Collection;
